suppose the IQ in certian population is normally distributed with mean 100 and standertd devation of 15 . 
A reasearcher wants to know if a new drug afftect IQ levels , so he recruits 20 patients to try it and records therir IQ .
the following code show how to perfoerm Z test 

In [1]:
from statsmodels.stats.weightstats import ztest as ztest


In [2]:
data =[88, 92, 94, 94, 96, 97,97,97,99,99,
      105, 109, 109, 109, 110, 112, 112, 113, 114, 115]

In [4]:
ztest(data,value=100)

(1.5976240527147705, 0.1101266701438426)

In [ ]:
(z score,p values)

In [ ]:
0.11 > 0.05   wqe accpet null hypo

In [ ]:
reject null hypo condition

p val < significan value  = reject null hypo

In [ ]:
# t test 

In [6]:
ages=[10,20,35,50,28, 40, 55, 18, 16, 56,30, 25, 43, 18, 30, 28,14,24, 16,17,32,35,26,27,65,18,43,23,21,20,19,70  ]

In [7]:
import numpy as np

In [8]:
ages_mean= np.mean(ages)
ages_mean

30.375

In [9]:
sample_size=10
age_sample=np.random.choice(ages,sample_size)

In [10]:
age_sample

array([35, 43, 16, 25, 30, 43, 28, 17, 20, 18])

In [11]:
from scipy.stats import ttest_1samp

In [12]:
ttest_1samp(age_sample,30)

Ttest_1sampResult(statistic=-0.7741838812189678, pvalue=0.4586756905451853)

In [ ]:
##########

In [16]:
import scipy.stats as stats
np.random.seed(6)
school_ages=stats.poisson.rvs(loc=18,mu=35,size=1500)
calssA_ages=stats.poisson.rvs(loc=18,mu=30,size=60)

In [17]:
school_ages

array([62, 59, 44, ..., 45, 52, 50])

In [18]:
calssA_ages

array([52, 46, 40, 40, 47, 50, 51, 45, 44, 52, 46, 53, 43, 44, 51, 50, 54,
       42, 54, 45, 61, 53, 49, 46, 47, 41, 45, 51, 43, 45, 48, 50, 40, 52,
       44, 55, 54, 40, 45, 46, 54, 42, 46, 35, 51, 51, 46, 48, 47, 35, 52,
       52, 39, 44, 48, 40, 42, 46, 47, 45])

In [19]:
calssA_ages.mean()

46.9

In [21]:
_,p_value=ttest_1samp(calssA_ages,school_ages.mean())

In [22]:
if p_value < 0.05 :
    print("reject H0")
else:
    print("accpect H0")

reject H0
